tunnel: agendamento
credentials-file: /DATA/cloudflared/.cloudflared/d6f1e2aa-6d7f-49ba-b7c1-6486f80e2b4b.json

ingress:
  - hostname: agendamento.deadzone.com.br
    service: http://192.168.1.100:8090
  - hostname: agendamento.agendamentos.app.br
    service: http://192.168.1.100:8090
  - hostname: navalha.deadzone.com.br
    service: http://192.168.1.100:8091
  - hostname: navalha.agendamentos.app.br
    service: http://192.168.1.100:8091
  - hostname: studiobeauty.agendamentos.app.br
    service: http://192.168.1.100:8094
  - hostname: studiobeleza.agendamentos.app.br
    service: http://192.168.1.100:8095
  - service: http_status:404
